In [1]:
import pandas as pd

In [2]:
stocks= pd.read_csv("D:/Project/Data-Sciences/pandas/13- style DataFrame/stock.csv")

In [3]:
stocks

       Date   Close    Volume Symbol
0  03-10-16   31.50  14070500   CSCO
1  03-10-16  112.52  21701800   AAPL
2  03-10-16   57.42  19189500   MSFT
3  04-10-16  113.00  29736800   AAPL
4  04-10-16   57.24  20085900   MSFT
5  04-10-16   31.35  18460400   CSCO
6  05-10-16   57.64  16726400   MSFT
7  05-10-16   31.59  11808600   CSCO
8  05-10-16  113.05  21453100   AAPL

In [4]:
stock= pd.read_csv("D:/Project/Data-Sciences/pandas/13- style DataFrame/stock.csv", index_col="Date")

In [5]:
stock.head()

           Close    Volume Symbol
Date
03-10-16   31.50  14070500   CSCO
03-10-16  112.52  21701800   AAPL
03-10-16   57.42  19189500   MSFT
04-10-16  113.00  29736800   AAPL
04-10-16   57.24  20085900   MSFT

In [6]:
stocks.sort_index(inplace=True)

In [7]:
stocks.sort_index( )

       Date   Close    Volume Symbol
0  03-10-16   31.50  14070500   CSCO
1  03-10-16  112.52  21701800   AAPL
2  03-10-16   57.42  19189500   MSFT
3  04-10-16  113.00  29736800   AAPL
4  04-10-16   57.24  20085900   MSFT
5  04-10-16   31.35  18460400   CSCO
6  05-10-16   57.64  16726400   MSFT
7  05-10-16   31.59  11808600   CSCO
8  05-10-16  113.05  21453100   AAPL

 Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [8]:
web_data= pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [9]:
web_data1 = web_data.rename(columns={'Date':'date',
                                            'HomeTeam':'home_team',
                                            'AwayTeam':'away_team',
                                            'FTHG': 'home_goals',
                                            'FTAG': 'away_goals'})

Read HTML
Target Website: https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)

In [20]:
read_html = pd.read_html('https://www.bbc.com/sport/football/premier-league/table')

In [18]:
# read_html= pd.read_html('https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes#Series_overview')

In [24]:
read_html

[                         Team  Played  Won  Drawn  Lost  Goals For  \
 0                    1Arsenal      31   21      7     3         61
 1            2Manchester City      30   18      7     5         60
 2          3Manchester United      31   15     10     6         56
 3                4Aston Villa      31   16      6     9         42
 4                  5Liverpool      31   14      7    10         50
 5                    6Chelsea      31   13      9     9         53
 6                  7Brentford      31   13      7    11         46
 7                    8Everton      31   13      7    11         37
 8                     9Fulham      31   13      5    13         43
 9    10Brighton & Hove Albion      31   11     10    10         41
 10               11Sunderland      31   11     10    10         32
 11         12Newcastle United      31   12      6    13         44
 12          13AFC Bournemouth      31    9     15     7         46
 13           14Crystal Palace      30   10      9    11         33
 14             15Leeds United      31    7     12    12         37
 15        16Nottingham Forest      31    8      8    15         31
 16        17Tottenham Hotspur      31    7      9    15         40
 17          18West Ham United      31    7      8    16         36
 18                  19Burnley      31    4      8    19         33
 19  20Wolverhampton Wanderers      31    3      8    20         24

     Goals Against  Goal Difference  Points  \
 0              22               39      70
 1              28               32      61
 2              43               13      55
 3              37                5      54
 4              42                8      49
 5              38               15      48
 6              42                4      46
 7              35                2      46
 8              44               -1      44
 9              37                4      43
 10             36               -4      43
 11             45               -1      42
 12             48               -2      42
 13             35               -2      39
 14             48              -11      33
 15             43              -12      32
 16             50              -10      30
 17             57              -21      29
 18             61              -28      20
 19             54              -30      17

                      Form, Last 6 games, Oldest first
 0   DResult DrawDResult DrawWResult WinWResult Win...
 1   WResult WinWResult WinWResult WinWResult WinDR...
 2   DResult DrawWResult WinWResult WinLResult Loss...
 3   WResult WinDResult DrawLResult LossLResult Los...
 4   WResult WinWResult WinWResult WinLResult LossD...
 5   DResult DrawDResult DrawLResult LossWResult Wi...
 6   DResult DrawLResult LossWResult WinDResult Dra...
 7   LResult LossLResult LossWResult WinWResult Win...
 8   LResult LossWResult WinWResult WinLResult Loss...
 9   LResult LossWResult WinWResult WinLResult Loss...
 10  LResult LossLResult LossDResult DrawWResult Wi...
 11  WResult WinLResult LossLResult LossWResult Win...
 12  WResult WinDResult DrawDResult DrawDResult Dra...
 13  WResult WinLResult LossWResult WinLResult Loss...
 14  DResult DrawDResult DrawLResult LossLResult Lo...
 15  DResult DrawLResult LossLResult LossDResult Dr...
 16  LResult LossLResult LossLResult LossLResult Lo...
 17  DResult DrawDResult DrawLResult LossWResult Wi...
 18  WResult WinDResult DrawLResult LossLResult Los...
 19  DResult DrawDResult DrawLResult LossWResult Wi...  ]